apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-config
  namespace: fleet-default
spec:
  branch: master
  correctDrift:
    enabled: false
  insecureSkipTLSVerify: false
  paths:
    - bundles/cert-manager
    - bundles/external-secrets-operator
    - bundles/external-secrets-operator-config
  repo: https://git.sr.ht/~mhahl/sigaint-rke2
  targets:
    - clusterName: lan-rke2-dmz