---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: cert-manager
    name: cert-manager
    version: 1.3.17
    repo: oci://registry-1.docker.io/bitnamicharts/cert-manager
    namespace: cert-manager